### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by sdsmith3** [shridhar-tl/jira-assistant#126]
Hey! I installed this addon today (v 0.95) and it successfully integrated with my JIRA instance (JIRA Server), but no data is showing up. It pulls some info - like it can see my JIRA avatar, and I can filter certain projects and such, but my Open Issues is blank (see attached), and when I try to search for a specific issue to bookmark, I get "None of the ticket numbers provided are valid." Any ideas what might be wrong? Thanks so much, this addon looks amazing :)

![jira_assistant_bug](https://user-images.githubusercontent.com/61211909/74784211-6bb69300-5275-11ea-913e-9c54af4b859f.png)

**Comment by Che994** [comment]
Same issue :( 
![image](https://user-images.githubusercontent.com/42790577/74804759-3064a480-5307-11ea-9741-d6fc2e06d161.png)

**Comment by piranha79** [comment]
What's your guys exact Chrome version?

**Comment by shkodaba** [comment]
The same problem (don't see any data in Worklog).
plugin 0.94
Chrome 79.0.3945.130

**Comment by sdsmith3** [comment]
I am actually getting this in Firefox - 73.0.1 (64 bit)

**Comment by piranha79** [comment]
@sdsmith3 looks like this is broken starting with the version 0.94 and still working in 0.93. I grabbed myself a copy of version 0.93 here https://github.com/shridhar-tl/jira-assistant/tree/master/release/firefox and manually installed it in firefox. Just in case you need a temporary workaround cause Jira Assistant is making your life much easier as it is the case for me.

**Comment by shkodaba** [comment]
Looks like it works after update to 0.96.
But still shows "Unable to connect to server".

**Comment by DayongW** [comment]
Something wrong with the worklog report. The data can NOT be rendered. 
![image](https://user-images.githubusercontent.com/33467667/75645063-7a576e00-5ca9-11ea-96f5-37647b21f1df.png)

**Comment by manasa08april** [comment]
I am still facing the same issue 
![image](https://user-images.githubusercontent.com/60995998/75649972-a6a7c600-5c7a-11ea-9f61-dec5d87c3c9b.png)

**Comment by shridhar-tl** [comment]
@manasa08april - You will have to be authenticated in Jira when you try to integrate it. This message states that you are not authenticated.

If you are already authenticated, can you check the console and network tab for any issues and post the screenshot? When you post it please ensure you hide the confidential information like domain name, user id, email, etc if any.

**Comment by shridhar-tl** [comment]
@DayongW - Can you check the console / network tab and see what is the error you are getting? Hope you are using Jira Assistant v0.97.

I have received confirmation from few users that the issue has been resolved and hence I feel your version would have not updated when you check or their could be some other issue.

**Comment by DayongW** [comment]
> @DayongW - Can you check the console / network tab and see what is the error you are getting? Hope you are using Jira Assistant v0.97.
> 
> I have received confirmation from few users that the issue has been resolved and hence I feel your version would have not updated when you check or their could be some other issue.

Hi @shridhar-tl , yes. Chrome just updated to v0.97. The issue is gone, so with my previous set group.

**Comment by manasa08april** [comment]
There are no error on console or network  tab. I m authenticated in jira

**Comment by manasa08april** [comment]
I am still facing issues with the worklog report
![image](https://user-images.githubusercontent.com/60995998/76392464-98069080-6397-11ea-9872-aedfcbe78d8d.png)
Getting the above error.
The reports are coming out blank.

**Comment by shridhar-tl** [comment]
@manasa08april - Can you check the network tab and see what is being passed as jql to server and send me the jql. This could be also caused by some custom jql you have written in worklog report. Check if you have any custom jql from config of worklog report JQL tab.

**Comment by shridhar-tl** [comment]
Closing this ticket assuming this issues has been resolved now. If any of you still face any issue please feel free to raise a new ticket.

@manasa08april - As no reply is received from you, I hope your issues is also resolved. If you still face any issue, then please raise a new ticket.
