### ISSUE TITLE
Unable to add new users to a group

### ISSUE THREAD

**Issue by emaillenin** [shridhar-tl/jira-assistant#148]
From the user groups pages (`#/2/settings/usergroups`), I am trying to add an user to an existing group.

A call is made to `/rest/api/2/user/search?maxResults=10&startAt=0&username=<search_query>` and the response is:

```
{
  "errorMessages": [
    "The query parameter 'username' is not supported in GDPR strict mode."
  ],
  "errors": {}
}
```

The suggested fix it to use `query` instead of `username` as the query parameter.

Eg. `/rest/api/2/user/search?maxResults=10&startAt=0&query=<search_query>`

See https://community.atlassian.com/t5/Jira-questions/The-query-parameter-username-is-not-supported-in-GDPR-strict/qaq-p/1345106

**Comment by shridhar-tl** [comment]
Hi @emaillenin - This fix is already done before a month back itself and you can see the change in following link. But unfortunately due to current lock down situation, this issue along with lot more fixes / enhancements are waiting to be published due to some issue with web store publishing process. I keep trying to publish it, but I am not getting enough support from web store dev support team. Hence I request your patience till the issue is sorted out.

Sourcecode url: https://github.com/shridhar-tl/jira-assistant/blob/develop/src/_constants.js  (Line No: 17 as of today)

**Comment by emaillenin** [comment]
@shridhar-tl oh okay, thanks for the update. I tried the latest version for Firefox and it seems fixed there. I'll use Firefox until this is resolved in Chrome.

**Comment by rahulingle1989** [comment]
Hi @shridhar-tl  
   I have been using the JIRA add on in JIRA Assitant for a while now, it's absolutely great.  However, for the last few days, I am unable to use it effectively. 
   could you fix the issue as soon as possible?
Thanks In Advance.

**Comment by shridhar-tl** [comment]
Hi @rahulingle1989 - I know you are facing some issue with Jira Assistant for chrome. Those issues has been fixed as well. But as mentioned earlier, their are some issue with chrome webstore for publishing and due to lockdown situations, I am not getting any support from webstore dev support team. Infact v0.98 is already published but awaiting approval in webstore, which resolves your issue and also has some more enhancements.

Hence I am requesting you to please wait for some more time until publish is approved.

**Comment by adrian-moisa** [comment]
![image](https://user-images.githubusercontent.com/11160141/79850538-c3d05980-83cc-11ea-94c6-ea5862f9ed2e.png)
I have exactly the same issue. I suppose I'll use Firefox meanwhile for the report.

**Comment by shridhar-tl** [comment]
I am still facing issue publishing to Chrome web store. But latest updates (i.e. v1.3) are published to Firefox, Edge and Opera already. Hope all the issues with Firefox should have already got resolved by now.

Chrome users please be patient or use Firefox version temporarily to help with your activities. Apologies for all the inconvenience caused.

**Comment by shridhar-tl** [comment]
This fix is published now in chrome extension as well. So you should see it working going forward. Thank you all for your patience. But for getting the fix published to chrome, some permissions given to chrome extensions were removed to get the approval in review process. As a result some of the minor features were removed as well. More in particular, Report Builder feature, excel export feature, first time integration, etc., may face some issues / change in the way of implementation.

To know exactly what is impacted, see version history in the extension.

**Comment by blis5fool** [comment]
Hi. I'm using chromium based Edge. I've been facing this issue. The extension in Microsoft Store is version 1.1, so I've tried installing the extension from Chrome Web Store which is version 1.3, but the same issue is still encountered. Not urgent but just noting down my observation here.

**Comment by shridhar-tl** [comment]
@blis5fool - I had already published v1.4 which solves the issue. You can review the changes in above commit  (i.e. b686455).

For few set of users search works on one way and for another set other way works. Hence the fix I gave in 1.3 has broken for some of the user's while resolving the issue for other set of users. For edge updates should be available soon (may be within max 24 hours from now) than other browsers as review process is quick.

**Comment by blis5fool** [comment]
Awesome. I see that my extension was updated to 1.4 and I've tested it and it's working.
Thanks for the update! Really appreciate it!

**Comment by shridhar-tl** [comment]
@emaillenin @adrian-moisa @rahulingle1989 - Now this issue has been resolved for all the browsers. Based on confirmation from @blis5fool closing this issue.

In case if you face any other issue please feel free to raise a new issue.
