### ISSUE TITLE
I don't see all of my jira Boards in Sprint Report > Rapid view

### ISSUE THREAD

**Issue by jacuaPL** [shridhar-tl/jira-assistant#245]
Hello,
around 3 months ago I saw the problem. 
When I open JA, Sprint Report > Rapid view, I don't see a full list of my Jira Boards, so I can't generate reports.

So far it works perfect, when I clicked Rapid view I saw full list and I can open right report. Anyone can help? ;)

**Comment by shridhar-tl** [comment]
Hi @jacuaPL - Do you have more than 50 boards in your JIRA instance? If so then JIRA responds with first 50 boards only and may be so far your board was one of that. But my assumption is due to some of the latest changes, in your or someone else's board, now the ordering changed and your board does not fall under that first 50. That could be the reason why you are not seeing your board now.

If my assumption is correct, this issue is already resolved in latest version of Jira Assistant i.e. v2.43. It is already available in Web version of Jira Assistant. Please try accessing https://app.jiraassistant.com and see if your issue is resolved in that web version. If yes, then temporarily you can use web version and in a weeks time it would be published for extension as well.

Please let me know if this helps.

**Comment by jacuaPL** [comment]
Yes, I have more than 50 boards and I see only first 50. 
But I don't see JA v2.43, it's still v2.42 so this issue is not solved in this version.
How can I update webversion?
<img width="935" alt="JA_version_web" src="https://user-images.githubusercontent.com/104375724/206655745-1eee10ca-155d-4b0c-b882-0fd2d2634774.png">

**Comment by jacuaPL** [comment]
Yes, I have more than 50 boards and I see only first 50.

But I don't see JA v2.43, it's still v2.42 so this issue is not solved in this version.
How can I update webversion?

<img width="935" alt="JA_version_web" src="https://user-images.githubusercontent.com/104375724/206656010-76fa939c-2f32-412b-a0fc-00fe5f95c9f3.png">

**Comment by shridhar-tl** [comment]
Already you should see it on Web version. Web version is always up to date with latest build. Update info is basically for information only and not an indicator of what is the current version.

Any way, have you tried it in Wen version?

**Comment by jacuaPL** [comment]
Yes, as you see on screenshoot, I'm on webversion and it doesn't work. Still I see only 50 first Boards and when I write correct Board name, it's not searched :( Any ideas?

**Comment by jacuaPL** [comment]
Hello, unfortunatelly it still doesn't work. I see on my webversion
Build: 13-Dec-2022 06:04:31 AM

**Comment by shridhar-tl** [comment]
Hi, I'm not sure what is stopping your board from displaying. Currently it list out only scrum boards and earlier it use to list out simple and kanban board as well. To view sprint report, you will need only sprint boards and so I had filtered it to pull only sprint boards so that data being pulled is reduced.

By any chance you are not trying to find a kanban board in that list right?

I am definitely sure that v2.43 is listing out all the sprint boards. By the way, board name may be different that project name. So hopefully you are not searching with project name I believe. Please ensure that as well.

to further debug the issue, you can capture network logs and see if all the boards are being pulled and your board is listed in that data.

If you  try from extension (v2.43 or above), you can just press F12 and look at the network logs.

If you try from web version (which is always latest), you cannot look at network request by pressing F12. All requests would be routed through extension only and for that you need to open devtools of background service worker by following the steps below:

Step 1: Navigate to "chrome://extensions" from chrome
Step 2: Turn on "Developer mode" from top right corner of the browser
![image](https://user-images.githubusercontent.com/37339683/208605857-1b5f0b56-d47f-4090-bf09-466988f442cf.png)

Step 3: Click "service worker" link which would open dev tools.
![image](https://user-images.githubusercontent.com/37339683/208606061-2f024ebd-6ac1-41d7-af55-323643add24c.png)

From devtools, network tab, you can track all the network request and there you can filter for api calls for "rest/agile/1.0/board" or "rest/greenhopper/1.0/rapidview" whatever is available.

If it exists, then search for your board from the response and see if its listed. Also look at console for any errors or warnings and if you find something please send the screenshots of the same.

**Comment by shridhar-tl** [comment]
If you were still not able to figure out the issue, please send me a mail where I can provide more quick support. You can find my mail id from the website.

**Comment by shridhar-tl** [comment]
Hi @jacuaPL - Please have a look at my comments above and see if you were able to resolve your issue.

I am closing this issue as I was not able to reproduce it in any environments and I had verified it with my other sources as well and all working well as far as I know.

 If you still face any issues, please feel free to reopen this issue with some more details. You can contact me via mail as well where I would be able to help you with additional details.
